---
# tasks file for ipxe

- name: install python-firewall bindings to open port
  dnf: name=python-firewall state=latest

- name: install nginx
  dnf: name=nginx state=present
  register: nginx_install

- name: update nginx
  dnf: name=nginx state=latest

- name: configure nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf mode=0644 owner=root group=root
  notify:
   - restart nginx

  #configure the default site only if installing the role for the first time
  #since roles that build on top of this will want to remove it
- name: configure default site
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf mode=0644 owner=root group=root
  when: nginx_install.changed

- meta: flush_handlers

- name: ensure nginx is running
  service: name=nginx state=running enabled=yes
